package:
  name: pynemo
  version: "0.2"
#source:
#  path: ../
#  svn_url: http://ccpforge.cse.rl.ac.uk/svn/pynemo/trunk/Python

build:
  preserve_egg_dir: yes
#  number: 0
  
requirements:
  build:
    - python
    - numpy
    - setuptools
    - scipy
    - netcdf4
    - matplotlib
    - basemap
    - thredds_crawler

  run:
    - python
    - numpy
    - scipy
    - netcdf4
    - matplotlib
    - basemap
    - thredds_crawler

#test:
#  files:
#    - ../data/grid_C/NNA_R12_bathy_meter_bench.nc
#  requires:
#    - nose
#  imports:
#    - nosetests
about:
  home: http://ccpforge.cse.rl.ac.uk/gf/project/pynemo/
  license:  CeCILL license
